### ISSUE TITLE
一个疑问: ?? 为什么 Clients和 Candidates/职位页面 显示空白 ??

### ISSUE THREAD

**Issue by LucyJoo** [UReact/CRM_feedback#1]
CRM系统 Clients 页面显示空白 看不到客户数据 
(PS:截图失败 乱码 所以只写了问题）

如果是数据还未转移进去 
我就没有什么其他疑问了

**Comment by ThomasLiu** [comment]
@LucyJoo 提供一些截图

**Comment by LucyJoo** [comment]
Lucy Joo (朱俊翔) 
Marketing Manager (市场经理) 
GuideinChina & HiredChina.com (在华外国人才网) 
lucy.joo@hiredchina.com 
+86 755 21654992   +86 173-2445-2747 
Facebook LinkedIn Twitter YouTube  	    
This message contains information that may be privileged or confidential and is the property of GuideinChina & HiredChina.com. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.
 Make it easier for you to recruit a qualified foreign talent. Hiredchina.com 
 让你更容易招到适合的外籍人才 Hiredchina.com


------------------------------------------------------------------
发件人：Thomas Lau <notifications@github.com>
发送时间：2019年2月1日(星期五) 12:42
收件人：UReact/CRM_feedback <CRM_feedback@noreply.github.com>
抄　送：Lucy Joo <lucy.joo@hiredchina.com>; Mention <mention@noreply.github.com>
主　题：Re: [UReact/CRM_feedback] 一个疑问: ?? 为什么 Clients和 Candidates/职位页面 显示空白 ?? (#1)

@LucyJoo 提供一些截图
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



    超大附件列表            微信图片_20190201100316.jpg  [57KB]
        进入下载页面  http://mail.hiredchina.com/alimail/openLinks/downloadMimeMetaDiskBigAttach?id=netdiskid%3Av001%3Afile%3ADzzzzzzNqVF%3BhTTM%2Ff2Gdni925%2FEiMgdbHyh%2F%2BV0Kce5w57vyU2tOy2sp%2BDHWVan3HFXovvb0IJiRG6Ng3Q9IqTjK50JGJd6Z7fwjjHNy9rOYPq6lDfcPoiTg9D2AgiG%2FXUE%2FMvvFwUq            微信图片_20190201100325.jpg  [73KB]
        进入下载页面  http://mail.hiredchina.com/alimail/openLinks/downloadMimeMetaDiskBigAttach?id=netdiskid%3Av001%3Afile%3ADzzzzzzNqVE%3BhTTM%2Ff2Gdni925%2FEiMgdbHyh%2F%2BV0Kce5w57vyU2tOy2sp%2BDHWVan3HFXovvb0IJiRG6Ng3Q9IqTjK50JGJd6Z7fwjjHNy9rOYPq6lDfcPoiTg9D2AgiG%2Fd0It%2Ba3V6UZ

**Comment by jimmywong123** [comment]
那个时候数据还没有转移过去，现在已经有数据了。
