### ISSUE TITLE
Labels 功能优化建议

### ISSUE THREAD

**Issue by ThomasLiu** [UReact/CRM_feedback#2]
* 在列表上也有分页，显示我自己有多少的给Labels的数据
* labels 选择的时候，统计出每个labels 的数据，让我在选择之前有个大概了解

**Comment by ThomasLiu** [comment]
* 在下面的数据 也显示这个数据有哪些Labels
* 可以在数据列表上直接的管理Labels，单独或者批量的对数据增加或者删除labels

**Comment by jimmywong123** [comment]
现在可以在label界面一次性删除与此label关联的简历关系，也可以批量添加标签。
![image](https://user-images.githubusercontent.com/42126331/58320821-26347900-7e4f-11e9-85de-9adff84befdc.png)
![image](https://user-images.githubusercontent.com/42126331/58320942-609e1600-7e4f-11e9-84d9-df8fe5bd2c02.png)
